default_config:

logger:
  default: info
  logs:
    custom_components.polleninformation_at: debug

frontend:

config:

history:

logbook:

system_log:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
