name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.14

      - name: ZIP polleninformation_at dir
        run: |
          cd ${{ github.workspace }}/custom_components/polleninformation_at
          zip polleninformation_at.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/polleninformation_at/polleninformation_at.zip
          asset_name: polleninformation_at.zip
          tag: ${{ github.ref }}
          overwrite: true