name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release_zip_file:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Read version from manifest
        id: version
        run: |
          VERSION=$(jq -r '.version' custom_components/polleninformation_at/manifest.json)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: ZIP polleninformation_at dir
        run: |
          cd ${{ github.workspace }}/custom_components/polleninformation_at
          zip polleninformation_at.zip -r ./

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          draft: true

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          files: ${{ github.workspace }}/custom_components/polleninformation_at/polleninformation_at.zip